<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="2">

  <testsuite name="tests"
    errors="1" failures="0" hostname="" id="" package="pom" skipped="1"
    tests="2" time="0.04100" timestamp="Fri, 24 Mar 2017 06:09:13 GMT">
  
    <testcase name="Open the website" time="0.04100" assertions="0">
    </testcase>
      <system-err>
          Error while running [Pom / Tests / Open the website]:

  ReferenceError: waitTime is not defined
    at goToSite (E:\strikingly\Project2\tests\pom\utils.js:9:38)
    at Object.Open the website (E:\strikingly\Project2\tests\pom\tests.js:7:20)
    at Module.call (E:\strikingly\Project2\lib\nightwatch\lib\runner\module.js:62:34)
    at E:\strikingly\Project2\lib\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (E:\strikingly\Project2\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (E:\strikingly\Project2\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (E:\strikingly\Project2\node_modules\q\q.js:796:13)
    at E:\strikingly\Project2\node_modules\q\q.js:556:49
    at runSingle (E:\strikingly\Project2\node_modules\q\q.js:137:13)
    at flush (E:\strikingly\Project2\node_modules\q\q.js:125:13)
      </system-err>
  
  
    
    <testcase
      name="Go to site and add user and logout">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
